### ISSUE TITLE
some questions about code o ROME

### ISSUE THREAD

**Issue by wtma1999** [scalable-model-editing/unified-model-editing#1]
Thank you for your great work! 
I have a couple of questions regarding the implementation of the code, some of which arise from the ROME  itself.
Q1: Why is the left and right matrix multiplication of ROME inverted after calculating vectors k and v (in compute_v.py, line 201),  which is inconsistent with equation 2 of the paper, and When was the transposition operation implemented  on (C-1 k*)?
![1](https://github.com/scalable-model-editing/unified-model-editing/assets/140484126/a1448f8f-e362-47bd-ad35-821836714bcc)
Q2: I noticed that after editing, the k and v vectors are cached for future use, I think it's a great trick. Could this approach potentially mitigate the impact of sequence editing crashes to a certain extent? (In my understanding, it seems plausible.)
![2](https://github.com/scalable-model-editing/unified-model-editing/assets/140484126/a149ed1c-e41c-407b-9024-25c63992e897)

Thank you sincerely for your contributions! I eagerly await your response!

**Comment by akshat57** [comment]
Hey!

For Q2, Yes caching can be done but that is not the source of crashing due to sequential editing with ROME. We have identified the exact reason for that and will be sharing that in the next few days with ROME. 

For Q1, we do not use the original code of ROME as pointed out above. The implementation of ROME is done in line https://github.com/scalable-model-editing/unified-model-editing/blob/5787c18615c132b9fa9dee29555aeff5120039bf/unified_editing/unified_main.py#L231 . This implementation of ROME refers to this paper - https://arxiv.org/abs/2403.07175

Again, more details on exact reasons for crashing of ROME with sequential are coming soon, but this code can be used to do sequential editing with ROME without crashing.

**Comment by wtma1999** [comment]
Thank you for your answer and I am looking forward to your new work！

**Comment by akshat57** [comment]
Hi, 

The latest version of our paper to point the exact differences mathematically that lead to disabling edits with ROME - https://arxiv.org/abs/2403.07175

We have also updated the repository of the codebase to reflect these changes - https://github.com/scalable-model-editing/rebuilding-rome

**Comment by wtma1999** [comment]
Thank you for your response. Your recent work is truly inspiring.
I have some new ideas that I would like to discuss with you.
Q1: Does disabling edits  in paper represent  some bad cases？Do these data points consistently show larger values of |∆|?  My intuition suggests that this could be contingent on the order of edits, as the positions of these data points within the sequence may determine which the edited models it encounters when editing.

Q2: As mentioned  
> While r-ROME does that and enables sequential editing with ROME, downstream performance degradation and decreased stability (as observed from increasing |∆|) still occurs at scale. 

This decline could potentially be attributed to R-ROME's limited consideration of the cumulative impact on prior edits. I hypothesize that updating C0​ in equation 2 by incorporating a cache of current edit knowledge could potentially mitigate this issue, as previously discussed.
>Q2: I noticed that after editing, the k and v vectors are cached for future use, I think it's a great trick. Could this approach potentially mitigate the impact of sequence editing crashes to a certain extent? (In my understanding, it seems plausible.)

Thank you sincerely for your contributions!

**Comment by akshat57** [comment]
Hi, 

Regarding your comment about disabling edits representing bad cases - that could be the case. This would require some more detailed analysis. 

Regarding your comment about updating C0 in equation 2, it will definitely help in not forgetting previous facts - something we observed in this paper - https://arxiv.org/abs/2401.07453. If it will help with degradation or not, I'm not sure. 

If you want to chat more about this, feel free to email me - akshat.gupta@berkeley.edu

**Comment by wtma1999** [comment]
Thank you sincerely for your reply！
